/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as ApiPublicResetAdminOneshotRouteImport } from './routes/api/public/reset-admin-oneshot'
import { Route as ApiPublicOrdersRouteImport } from './routes/api/public/orders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResetAdminOneshotRoute =
  ApiPublicResetAdminOneshotRouteImport.update({
    id: '/api/public/reset-admin-oneshot',
    path: '/api/public/reset-admin-oneshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOrdersRoute = ApiPublicOrdersRouteImport.update({
  id: '/api/public/orders',
  path: '/api/public/orders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/reset-admin-oneshot': typeof ApiPublicResetAdminOneshotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/reset-admin-oneshot': typeof ApiPublicResetAdminOneshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/orders': typeof ApiPublicOrdersRoute
  '/api/public/reset-admin-oneshot': typeof ApiPublicResetAdminOneshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/import'
    | '/admin/login'
    | '/admin/'
    | '/api/public/orders'
    | '/api/public/reset-admin-oneshot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/import'
    | '/admin/login'
    | '/admin'
    | '/api/public/orders'
    | '/api/public/reset-admin-oneshot'
  id:
    | '__root__'
    | '/'
    | '/admin/import'
    | '/admin/login'
    | '/admin/'
    | '/api/public/orders'
    | '/api/public/reset-admin-oneshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicOrdersRoute: typeof ApiPublicOrdersRoute
  ApiPublicResetAdminOneshotRoute: typeof ApiPublicResetAdminOneshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reset-admin-oneshot': {
      id: '/api/public/reset-admin-oneshot'
      path: '/api/public/reset-admin-oneshot'
      fullPath: '/api/public/reset-admin-oneshot'
      preLoaderRoute: typeof ApiPublicResetAdminOneshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/orders': {
      id: '/api/public/orders'
      path: '/api/public/orders'
      fullPath: '/api/public/orders'
      preLoaderRoute: typeof ApiPublicOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminImportRoute: AdminImportRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicOrdersRoute: ApiPublicOrdersRoute,
  ApiPublicResetAdminOneshotRoute: ApiPublicResetAdminOneshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
